//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home_en: Home_En;
  home_enConnection: Home_EnConnection;
  home_si: Home_Si;
  home_siConnection: Home_SiConnection;
  home_ta: Home_Ta;
  home_taConnection: Home_TaConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHome_EnArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHome_EnConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Home_EnFilter>;
};


export type QueryHome_SiArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHome_SiConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Home_SiFilter>;
};


export type QueryHome_TaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHome_TaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Home_TaFilter>;
};

export type DocumentFilter = {
  home_en?: InputMaybe<Home_EnFilter>;
  home_si?: InputMaybe<Home_SiFilter>;
  home_ta?: InputMaybe<Home_TaFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home_En | Home_Si | Home_Ta | Folder;

export type Home_EnHeroCta_Primary = {
  __typename?: 'Home_enHeroCta_primary';
  text: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type Home_EnHeroCta_Secondary = {
  __typename?: 'Home_enHeroCta_secondary';
  text: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type Home_EnHero = {
  __typename?: 'Home_enHero';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  cta_primary?: Maybe<Home_EnHeroCta_Primary>;
  cta_secondary?: Maybe<Home_EnHeroCta_Secondary>;
};

export type Home_EnMission_Statement = {
  __typename?: 'Home_enMission_statement';
  title: Scalars['String']['output'];
  content: Scalars['String']['output'];
};

export type Home_EnFeatured_Departments = {
  __typename?: 'Home_enFeatured_departments';
  name: Scalars['String']['output'];
  description: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type Home_EnRecent_Events = {
  __typename?: 'Home_enRecent_events';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  time: Scalars['String']['output'];
  location: Scalars['String']['output'];
  description: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
};

export type Home_EnAnnouncements = {
  __typename?: 'Home_enAnnouncements';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  content: Scalars['String']['output'];
  priority?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
};

export type Home_EnStatistics = {
  __typename?: 'Home_enStatistics';
  number: Scalars['String']['output'];
  label: Scalars['String']['output'];
};

export type Home_EnQuick_Actions = {
  __typename?: 'Home_enQuick_actions';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  href: Scalars['String']['output'];
  color?: Maybe<Scalars['String']['output']>;
};

export type Home_EnNewsletter = {
  __typename?: 'Home_enNewsletter';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  placeholder: Scalars['String']['output'];
  button: Scalars['String']['output'];
  privacy?: Maybe<Scalars['String']['output']>;
};

export type Home_En = Node & Document & {
  __typename?: 'Home_en';
  hero?: Maybe<Home_EnHero>;
  mission_statement?: Maybe<Home_EnMission_Statement>;
  featured_departments?: Maybe<Array<Maybe<Home_EnFeatured_Departments>>>;
  recent_events?: Maybe<Array<Maybe<Home_EnRecent_Events>>>;
  announcements?: Maybe<Array<Maybe<Home_EnAnnouncements>>>;
  statistics?: Maybe<Array<Maybe<Home_EnStatistics>>>;
  quick_actions?: Maybe<Array<Maybe<Home_EnQuick_Actions>>>;
  newsletter?: Maybe<Home_EnNewsletter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type Home_EnHeroCta_PrimaryFilter = {
  text?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type Home_EnHeroCta_SecondaryFilter = {
  text?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type Home_EnHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  cta_primary?: InputMaybe<Home_EnHeroCta_PrimaryFilter>;
  cta_secondary?: InputMaybe<Home_EnHeroCta_SecondaryFilter>;
};

export type Home_EnMission_StatementFilter = {
  title?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
};

export type Home_EnFeatured_DepartmentsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type Home_EnRecent_EventsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  time?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  category?: InputMaybe<StringFilter>;
};

export type Home_EnAnnouncementsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  content?: InputMaybe<StringFilter>;
  priority?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
};

export type Home_EnStatisticsFilter = {
  number?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type Home_EnQuick_ActionsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type Home_EnNewsletterFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  placeholder?: InputMaybe<StringFilter>;
  button?: InputMaybe<StringFilter>;
  privacy?: InputMaybe<StringFilter>;
};

export type Home_EnFilter = {
  hero?: InputMaybe<Home_EnHeroFilter>;
  mission_statement?: InputMaybe<Home_EnMission_StatementFilter>;
  featured_departments?: InputMaybe<Home_EnFeatured_DepartmentsFilter>;
  recent_events?: InputMaybe<Home_EnRecent_EventsFilter>;
  announcements?: InputMaybe<Home_EnAnnouncementsFilter>;
  statistics?: InputMaybe<Home_EnStatisticsFilter>;
  quick_actions?: InputMaybe<Home_EnQuick_ActionsFilter>;
  newsletter?: InputMaybe<Home_EnNewsletterFilter>;
};

export type Home_EnConnectionEdges = {
  __typename?: 'Home_enConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home_En>;
};

export type Home_EnConnection = Connection & {
  __typename?: 'Home_enConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Home_EnConnectionEdges>>>;
};

export type Home_SiHeroCta_Primary = {
  __typename?: 'Home_siHeroCta_primary';
  text: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type Home_SiHeroCta_Secondary = {
  __typename?: 'Home_siHeroCta_secondary';
  text: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type Home_SiHero = {
  __typename?: 'Home_siHero';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  cta_primary?: Maybe<Home_SiHeroCta_Primary>;
  cta_secondary?: Maybe<Home_SiHeroCta_Secondary>;
};

export type Home_SiMission_Statement = {
  __typename?: 'Home_siMission_statement';
  title: Scalars['String']['output'];
  content: Scalars['String']['output'];
};

export type Home_SiFeatured_Departments = {
  __typename?: 'Home_siFeatured_departments';
  name: Scalars['String']['output'];
  description: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type Home_SiRecent_Events = {
  __typename?: 'Home_siRecent_events';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  time: Scalars['String']['output'];
  location: Scalars['String']['output'];
  description: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
};

export type Home_SiAnnouncements = {
  __typename?: 'Home_siAnnouncements';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  content: Scalars['String']['output'];
  priority?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
};

export type Home_SiStatistics = {
  __typename?: 'Home_siStatistics';
  number: Scalars['String']['output'];
  label: Scalars['String']['output'];
};

export type Home_SiQuick_Actions = {
  __typename?: 'Home_siQuick_actions';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  href: Scalars['String']['output'];
  color?: Maybe<Scalars['String']['output']>;
};

export type Home_SiNewsletter = {
  __typename?: 'Home_siNewsletter';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  placeholder: Scalars['String']['output'];
  button: Scalars['String']['output'];
  privacy?: Maybe<Scalars['String']['output']>;
};

export type Home_Si = Node & Document & {
  __typename?: 'Home_si';
  hero?: Maybe<Home_SiHero>;
  mission_statement?: Maybe<Home_SiMission_Statement>;
  featured_departments?: Maybe<Array<Maybe<Home_SiFeatured_Departments>>>;
  recent_events?: Maybe<Array<Maybe<Home_SiRecent_Events>>>;
  announcements?: Maybe<Array<Maybe<Home_SiAnnouncements>>>;
  statistics?: Maybe<Array<Maybe<Home_SiStatistics>>>;
  quick_actions?: Maybe<Array<Maybe<Home_SiQuick_Actions>>>;
  newsletter?: Maybe<Home_SiNewsletter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Home_SiHeroCta_PrimaryFilter = {
  text?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type Home_SiHeroCta_SecondaryFilter = {
  text?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type Home_SiHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  cta_primary?: InputMaybe<Home_SiHeroCta_PrimaryFilter>;
  cta_secondary?: InputMaybe<Home_SiHeroCta_SecondaryFilter>;
};

export type Home_SiMission_StatementFilter = {
  title?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
};

export type Home_SiFeatured_DepartmentsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type Home_SiRecent_EventsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  time?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  category?: InputMaybe<StringFilter>;
};

export type Home_SiAnnouncementsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  content?: InputMaybe<StringFilter>;
  priority?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
};

export type Home_SiStatisticsFilter = {
  number?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type Home_SiQuick_ActionsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type Home_SiNewsletterFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  placeholder?: InputMaybe<StringFilter>;
  button?: InputMaybe<StringFilter>;
  privacy?: InputMaybe<StringFilter>;
};

export type Home_SiFilter = {
  hero?: InputMaybe<Home_SiHeroFilter>;
  mission_statement?: InputMaybe<Home_SiMission_StatementFilter>;
  featured_departments?: InputMaybe<Home_SiFeatured_DepartmentsFilter>;
  recent_events?: InputMaybe<Home_SiRecent_EventsFilter>;
  announcements?: InputMaybe<Home_SiAnnouncementsFilter>;
  statistics?: InputMaybe<Home_SiStatisticsFilter>;
  quick_actions?: InputMaybe<Home_SiQuick_ActionsFilter>;
  newsletter?: InputMaybe<Home_SiNewsletterFilter>;
};

export type Home_SiConnectionEdges = {
  __typename?: 'Home_siConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home_Si>;
};

export type Home_SiConnection = Connection & {
  __typename?: 'Home_siConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Home_SiConnectionEdges>>>;
};

export type Home_TaHeroCta_Primary = {
  __typename?: 'Home_taHeroCta_primary';
  text: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type Home_TaHeroCta_Secondary = {
  __typename?: 'Home_taHeroCta_secondary';
  text: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type Home_TaHero = {
  __typename?: 'Home_taHero';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  cta_primary?: Maybe<Home_TaHeroCta_Primary>;
  cta_secondary?: Maybe<Home_TaHeroCta_Secondary>;
};

export type Home_TaMission_Statement = {
  __typename?: 'Home_taMission_statement';
  title: Scalars['String']['output'];
  content: Scalars['String']['output'];
};

export type Home_TaFeatured_Departments = {
  __typename?: 'Home_taFeatured_departments';
  name: Scalars['String']['output'];
  description: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  href: Scalars['String']['output'];
};

export type Home_TaRecent_Events = {
  __typename?: 'Home_taRecent_events';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  time: Scalars['String']['output'];
  location: Scalars['String']['output'];
  description: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
};

export type Home_TaAnnouncements = {
  __typename?: 'Home_taAnnouncements';
  title: Scalars['String']['output'];
  date: Scalars['String']['output'];
  content: Scalars['String']['output'];
  priority?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
};

export type Home_TaStatistics = {
  __typename?: 'Home_taStatistics';
  number: Scalars['String']['output'];
  label: Scalars['String']['output'];
};

export type Home_TaQuick_Actions = {
  __typename?: 'Home_taQuick_actions';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  icon: Scalars['String']['output'];
  href: Scalars['String']['output'];
  color?: Maybe<Scalars['String']['output']>;
};

export type Home_TaNewsletter = {
  __typename?: 'Home_taNewsletter';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  placeholder: Scalars['String']['output'];
  button: Scalars['String']['output'];
  privacy?: Maybe<Scalars['String']['output']>;
};

export type Home_Ta = Node & Document & {
  __typename?: 'Home_ta';
  hero?: Maybe<Home_TaHero>;
  mission_statement?: Maybe<Home_TaMission_Statement>;
  featured_departments?: Maybe<Array<Maybe<Home_TaFeatured_Departments>>>;
  recent_events?: Maybe<Array<Maybe<Home_TaRecent_Events>>>;
  announcements?: Maybe<Array<Maybe<Home_TaAnnouncements>>>;
  statistics?: Maybe<Array<Maybe<Home_TaStatistics>>>;
  quick_actions?: Maybe<Array<Maybe<Home_TaQuick_Actions>>>;
  newsletter?: Maybe<Home_TaNewsletter>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type Home_TaHeroCta_PrimaryFilter = {
  text?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type Home_TaHeroCta_SecondaryFilter = {
  text?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type Home_TaHeroFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  cta_primary?: InputMaybe<Home_TaHeroCta_PrimaryFilter>;
  cta_secondary?: InputMaybe<Home_TaHeroCta_SecondaryFilter>;
};

export type Home_TaMission_StatementFilter = {
  title?: InputMaybe<StringFilter>;
  content?: InputMaybe<StringFilter>;
};

export type Home_TaFeatured_DepartmentsFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
};

export type Home_TaRecent_EventsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  time?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  category?: InputMaybe<StringFilter>;
};

export type Home_TaAnnouncementsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  content?: InputMaybe<StringFilter>;
  priority?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
};

export type Home_TaStatisticsFilter = {
  number?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type Home_TaQuick_ActionsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  color?: InputMaybe<StringFilter>;
};

export type Home_TaNewsletterFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  placeholder?: InputMaybe<StringFilter>;
  button?: InputMaybe<StringFilter>;
  privacy?: InputMaybe<StringFilter>;
};

export type Home_TaFilter = {
  hero?: InputMaybe<Home_TaHeroFilter>;
  mission_statement?: InputMaybe<Home_TaMission_StatementFilter>;
  featured_departments?: InputMaybe<Home_TaFeatured_DepartmentsFilter>;
  recent_events?: InputMaybe<Home_TaRecent_EventsFilter>;
  announcements?: InputMaybe<Home_TaAnnouncementsFilter>;
  statistics?: InputMaybe<Home_TaStatisticsFilter>;
  quick_actions?: InputMaybe<Home_TaQuick_ActionsFilter>;
  newsletter?: InputMaybe<Home_TaNewsletterFilter>;
};

export type Home_TaConnectionEdges = {
  __typename?: 'Home_taConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home_Ta>;
};

export type Home_TaConnection = Connection & {
  __typename?: 'Home_taConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Home_TaConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome_en: Home_En;
  createHome_en: Home_En;
  updateHome_si: Home_Si;
  createHome_si: Home_Si;
  updateHome_ta: Home_Ta;
  createHome_ta: Home_Ta;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHome_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Home_EnMutation;
};


export type MutationCreateHome_EnArgs = {
  relativePath: Scalars['String']['input'];
  params: Home_EnMutation;
};


export type MutationUpdateHome_SiArgs = {
  relativePath: Scalars['String']['input'];
  params: Home_SiMutation;
};


export type MutationCreateHome_SiArgs = {
  relativePath: Scalars['String']['input'];
  params: Home_SiMutation;
};


export type MutationUpdateHome_TaArgs = {
  relativePath: Scalars['String']['input'];
  params: Home_TaMutation;
};


export type MutationCreateHome_TaArgs = {
  relativePath: Scalars['String']['input'];
  params: Home_TaMutation;
};

export type DocumentUpdateMutation = {
  home_en?: InputMaybe<Home_EnMutation>;
  home_si?: InputMaybe<Home_SiMutation>;
  home_ta?: InputMaybe<Home_TaMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home_en?: InputMaybe<Home_EnMutation>;
  home_si?: InputMaybe<Home_SiMutation>;
  home_ta?: InputMaybe<Home_TaMutation>;
};

export type Home_EnHeroCta_PrimaryMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type Home_EnHeroCta_SecondaryMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type Home_EnHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  cta_primary?: InputMaybe<Home_EnHeroCta_PrimaryMutation>;
  cta_secondary?: InputMaybe<Home_EnHeroCta_SecondaryMutation>;
};

export type Home_EnMission_StatementMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
};

export type Home_EnFeatured_DepartmentsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type Home_EnRecent_EventsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
};

export type Home_EnAnnouncementsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  priority?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
};

export type Home_EnStatisticsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type Home_EnQuick_ActionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
};

export type Home_EnNewsletterMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  placeholder?: InputMaybe<Scalars['String']['input']>;
  button?: InputMaybe<Scalars['String']['input']>;
  privacy?: InputMaybe<Scalars['String']['input']>;
};

export type Home_EnMutation = {
  hero?: InputMaybe<Home_EnHeroMutation>;
  mission_statement?: InputMaybe<Home_EnMission_StatementMutation>;
  featured_departments?: InputMaybe<Array<InputMaybe<Home_EnFeatured_DepartmentsMutation>>>;
  recent_events?: InputMaybe<Array<InputMaybe<Home_EnRecent_EventsMutation>>>;
  announcements?: InputMaybe<Array<InputMaybe<Home_EnAnnouncementsMutation>>>;
  statistics?: InputMaybe<Array<InputMaybe<Home_EnStatisticsMutation>>>;
  quick_actions?: InputMaybe<Array<InputMaybe<Home_EnQuick_ActionsMutation>>>;
  newsletter?: InputMaybe<Home_EnNewsletterMutation>;
};

export type Home_SiHeroCta_PrimaryMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type Home_SiHeroCta_SecondaryMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type Home_SiHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  cta_primary?: InputMaybe<Home_SiHeroCta_PrimaryMutation>;
  cta_secondary?: InputMaybe<Home_SiHeroCta_SecondaryMutation>;
};

export type Home_SiMission_StatementMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
};

export type Home_SiFeatured_DepartmentsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type Home_SiRecent_EventsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
};

export type Home_SiAnnouncementsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  priority?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
};

export type Home_SiStatisticsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type Home_SiQuick_ActionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
};

export type Home_SiNewsletterMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  placeholder?: InputMaybe<Scalars['String']['input']>;
  button?: InputMaybe<Scalars['String']['input']>;
  privacy?: InputMaybe<Scalars['String']['input']>;
};

export type Home_SiMutation = {
  hero?: InputMaybe<Home_SiHeroMutation>;
  mission_statement?: InputMaybe<Home_SiMission_StatementMutation>;
  featured_departments?: InputMaybe<Array<InputMaybe<Home_SiFeatured_DepartmentsMutation>>>;
  recent_events?: InputMaybe<Array<InputMaybe<Home_SiRecent_EventsMutation>>>;
  announcements?: InputMaybe<Array<InputMaybe<Home_SiAnnouncementsMutation>>>;
  statistics?: InputMaybe<Array<InputMaybe<Home_SiStatisticsMutation>>>;
  quick_actions?: InputMaybe<Array<InputMaybe<Home_SiQuick_ActionsMutation>>>;
  newsletter?: InputMaybe<Home_SiNewsletterMutation>;
};

export type Home_TaHeroCta_PrimaryMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type Home_TaHeroCta_SecondaryMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type Home_TaHeroMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  cta_primary?: InputMaybe<Home_TaHeroCta_PrimaryMutation>;
  cta_secondary?: InputMaybe<Home_TaHeroCta_SecondaryMutation>;
};

export type Home_TaMission_StatementMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
};

export type Home_TaFeatured_DepartmentsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
};

export type Home_TaRecent_EventsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
};

export type Home_TaAnnouncementsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  content?: InputMaybe<Scalars['String']['input']>;
  priority?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
};

export type Home_TaStatisticsMutation = {
  number?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type Home_TaQuick_ActionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  color?: InputMaybe<Scalars['String']['input']>;
};

export type Home_TaNewsletterMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  placeholder?: InputMaybe<Scalars['String']['input']>;
  button?: InputMaybe<Scalars['String']['input']>;
  privacy?: InputMaybe<Scalars['String']['input']>;
};

export type Home_TaMutation = {
  hero?: InputMaybe<Home_TaHeroMutation>;
  mission_statement?: InputMaybe<Home_TaMission_StatementMutation>;
  featured_departments?: InputMaybe<Array<InputMaybe<Home_TaFeatured_DepartmentsMutation>>>;
  recent_events?: InputMaybe<Array<InputMaybe<Home_TaRecent_EventsMutation>>>;
  announcements?: InputMaybe<Array<InputMaybe<Home_TaAnnouncementsMutation>>>;
  statistics?: InputMaybe<Array<InputMaybe<Home_TaStatisticsMutation>>>;
  quick_actions?: InputMaybe<Array<InputMaybe<Home_TaQuick_ActionsMutation>>>;
  newsletter?: InputMaybe<Home_TaNewsletterMutation>;
};

export type Home_EnPartsFragment = { __typename: 'Home_en', hero?: { __typename: 'Home_enHero', title: string, subtitle?: string | null, description?: string | null, cta_primary?: { __typename: 'Home_enHeroCta_primary', text: string, href: string } | null, cta_secondary?: { __typename: 'Home_enHeroCta_secondary', text: string, href: string } | null } | null, mission_statement?: { __typename: 'Home_enMission_statement', title: string, content: string } | null, featured_departments?: Array<{ __typename: 'Home_enFeatured_departments', name: string, description: string, icon: string, href: string } | null> | null, recent_events?: Array<{ __typename: 'Home_enRecent_events', title: string, date: string, time: string, location: string, description: string, image?: string | null, category?: string | null } | null> | null, announcements?: Array<{ __typename: 'Home_enAnnouncements', title: string, date: string, content: string, priority?: string | null, category?: string | null } | null> | null, statistics?: Array<{ __typename: 'Home_enStatistics', number: string, label: string } | null> | null, quick_actions?: Array<{ __typename: 'Home_enQuick_actions', title: string, description: string, icon: string, href: string, color?: string | null } | null> | null, newsletter?: { __typename: 'Home_enNewsletter', title: string, description: string, placeholder: string, button: string, privacy?: string | null } | null };

export type Home_SiPartsFragment = { __typename: 'Home_si', hero?: { __typename: 'Home_siHero', title: string, subtitle?: string | null, description?: string | null, cta_primary?: { __typename: 'Home_siHeroCta_primary', text: string, href: string } | null, cta_secondary?: { __typename: 'Home_siHeroCta_secondary', text: string, href: string } | null } | null, mission_statement?: { __typename: 'Home_siMission_statement', title: string, content: string } | null, featured_departments?: Array<{ __typename: 'Home_siFeatured_departments', name: string, description: string, icon: string, href: string } | null> | null, recent_events?: Array<{ __typename: 'Home_siRecent_events', title: string, date: string, time: string, location: string, description: string, image?: string | null, category?: string | null } | null> | null, announcements?: Array<{ __typename: 'Home_siAnnouncements', title: string, date: string, content: string, priority?: string | null, category?: string | null } | null> | null, statistics?: Array<{ __typename: 'Home_siStatistics', number: string, label: string } | null> | null, quick_actions?: Array<{ __typename: 'Home_siQuick_actions', title: string, description: string, icon: string, href: string, color?: string | null } | null> | null, newsletter?: { __typename: 'Home_siNewsletter', title: string, description: string, placeholder: string, button: string, privacy?: string | null } | null };

export type Home_TaPartsFragment = { __typename: 'Home_ta', hero?: { __typename: 'Home_taHero', title: string, subtitle?: string | null, description?: string | null, cta_primary?: { __typename: 'Home_taHeroCta_primary', text: string, href: string } | null, cta_secondary?: { __typename: 'Home_taHeroCta_secondary', text: string, href: string } | null } | null, mission_statement?: { __typename: 'Home_taMission_statement', title: string, content: string } | null, featured_departments?: Array<{ __typename: 'Home_taFeatured_departments', name: string, description: string, icon: string, href: string } | null> | null, recent_events?: Array<{ __typename: 'Home_taRecent_events', title: string, date: string, time: string, location: string, description: string, image?: string | null, category?: string | null } | null> | null, announcements?: Array<{ __typename: 'Home_taAnnouncements', title: string, date: string, content: string, priority?: string | null, category?: string | null } | null> | null, statistics?: Array<{ __typename: 'Home_taStatistics', number: string, label: string } | null> | null, quick_actions?: Array<{ __typename: 'Home_taQuick_actions', title: string, description: string, icon: string, href: string, color?: string | null } | null> | null, newsletter?: { __typename: 'Home_taNewsletter', title: string, description: string, placeholder: string, button: string, privacy?: string | null } | null };

export type Home_EnQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Home_EnQuery = { __typename?: 'Query', home_en: { __typename: 'Home_en', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'Home_enHero', title: string, subtitle?: string | null, description?: string | null, cta_primary?: { __typename: 'Home_enHeroCta_primary', text: string, href: string } | null, cta_secondary?: { __typename: 'Home_enHeroCta_secondary', text: string, href: string } | null } | null, mission_statement?: { __typename: 'Home_enMission_statement', title: string, content: string } | null, featured_departments?: Array<{ __typename: 'Home_enFeatured_departments', name: string, description: string, icon: string, href: string } | null> | null, recent_events?: Array<{ __typename: 'Home_enRecent_events', title: string, date: string, time: string, location: string, description: string, image?: string | null, category?: string | null } | null> | null, announcements?: Array<{ __typename: 'Home_enAnnouncements', title: string, date: string, content: string, priority?: string | null, category?: string | null } | null> | null, statistics?: Array<{ __typename: 'Home_enStatistics', number: string, label: string } | null> | null, quick_actions?: Array<{ __typename: 'Home_enQuick_actions', title: string, description: string, icon: string, href: string, color?: string | null } | null> | null, newsletter?: { __typename: 'Home_enNewsletter', title: string, description: string, placeholder: string, button: string, privacy?: string | null } | null } };

export type Home_EnConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Home_EnFilter>;
}>;


export type Home_EnConnectionQuery = { __typename?: 'Query', home_enConnection: { __typename?: 'Home_enConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Home_enConnectionEdges', cursor: string, node?: { __typename: 'Home_en', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'Home_enHero', title: string, subtitle?: string | null, description?: string | null, cta_primary?: { __typename: 'Home_enHeroCta_primary', text: string, href: string } | null, cta_secondary?: { __typename: 'Home_enHeroCta_secondary', text: string, href: string } | null } | null, mission_statement?: { __typename: 'Home_enMission_statement', title: string, content: string } | null, featured_departments?: Array<{ __typename: 'Home_enFeatured_departments', name: string, description: string, icon: string, href: string } | null> | null, recent_events?: Array<{ __typename: 'Home_enRecent_events', title: string, date: string, time: string, location: string, description: string, image?: string | null, category?: string | null } | null> | null, announcements?: Array<{ __typename: 'Home_enAnnouncements', title: string, date: string, content: string, priority?: string | null, category?: string | null } | null> | null, statistics?: Array<{ __typename: 'Home_enStatistics', number: string, label: string } | null> | null, quick_actions?: Array<{ __typename: 'Home_enQuick_actions', title: string, description: string, icon: string, href: string, color?: string | null } | null> | null, newsletter?: { __typename: 'Home_enNewsletter', title: string, description: string, placeholder: string, button: string, privacy?: string | null } | null } | null } | null> | null } };

export type Home_SiQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Home_SiQuery = { __typename?: 'Query', home_si: { __typename: 'Home_si', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'Home_siHero', title: string, subtitle?: string | null, description?: string | null, cta_primary?: { __typename: 'Home_siHeroCta_primary', text: string, href: string } | null, cta_secondary?: { __typename: 'Home_siHeroCta_secondary', text: string, href: string } | null } | null, mission_statement?: { __typename: 'Home_siMission_statement', title: string, content: string } | null, featured_departments?: Array<{ __typename: 'Home_siFeatured_departments', name: string, description: string, icon: string, href: string } | null> | null, recent_events?: Array<{ __typename: 'Home_siRecent_events', title: string, date: string, time: string, location: string, description: string, image?: string | null, category?: string | null } | null> | null, announcements?: Array<{ __typename: 'Home_siAnnouncements', title: string, date: string, content: string, priority?: string | null, category?: string | null } | null> | null, statistics?: Array<{ __typename: 'Home_siStatistics', number: string, label: string } | null> | null, quick_actions?: Array<{ __typename: 'Home_siQuick_actions', title: string, description: string, icon: string, href: string, color?: string | null } | null> | null, newsletter?: { __typename: 'Home_siNewsletter', title: string, description: string, placeholder: string, button: string, privacy?: string | null } | null } };

export type Home_SiConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Home_SiFilter>;
}>;


export type Home_SiConnectionQuery = { __typename?: 'Query', home_siConnection: { __typename?: 'Home_siConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Home_siConnectionEdges', cursor: string, node?: { __typename: 'Home_si', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'Home_siHero', title: string, subtitle?: string | null, description?: string | null, cta_primary?: { __typename: 'Home_siHeroCta_primary', text: string, href: string } | null, cta_secondary?: { __typename: 'Home_siHeroCta_secondary', text: string, href: string } | null } | null, mission_statement?: { __typename: 'Home_siMission_statement', title: string, content: string } | null, featured_departments?: Array<{ __typename: 'Home_siFeatured_departments', name: string, description: string, icon: string, href: string } | null> | null, recent_events?: Array<{ __typename: 'Home_siRecent_events', title: string, date: string, time: string, location: string, description: string, image?: string | null, category?: string | null } | null> | null, announcements?: Array<{ __typename: 'Home_siAnnouncements', title: string, date: string, content: string, priority?: string | null, category?: string | null } | null> | null, statistics?: Array<{ __typename: 'Home_siStatistics', number: string, label: string } | null> | null, quick_actions?: Array<{ __typename: 'Home_siQuick_actions', title: string, description: string, icon: string, href: string, color?: string | null } | null> | null, newsletter?: { __typename: 'Home_siNewsletter', title: string, description: string, placeholder: string, button: string, privacy?: string | null } | null } | null } | null> | null } };

export type Home_TaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type Home_TaQuery = { __typename?: 'Query', home_ta: { __typename: 'Home_ta', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'Home_taHero', title: string, subtitle?: string | null, description?: string | null, cta_primary?: { __typename: 'Home_taHeroCta_primary', text: string, href: string } | null, cta_secondary?: { __typename: 'Home_taHeroCta_secondary', text: string, href: string } | null } | null, mission_statement?: { __typename: 'Home_taMission_statement', title: string, content: string } | null, featured_departments?: Array<{ __typename: 'Home_taFeatured_departments', name: string, description: string, icon: string, href: string } | null> | null, recent_events?: Array<{ __typename: 'Home_taRecent_events', title: string, date: string, time: string, location: string, description: string, image?: string | null, category?: string | null } | null> | null, announcements?: Array<{ __typename: 'Home_taAnnouncements', title: string, date: string, content: string, priority?: string | null, category?: string | null } | null> | null, statistics?: Array<{ __typename: 'Home_taStatistics', number: string, label: string } | null> | null, quick_actions?: Array<{ __typename: 'Home_taQuick_actions', title: string, description: string, icon: string, href: string, color?: string | null } | null> | null, newsletter?: { __typename: 'Home_taNewsletter', title: string, description: string, placeholder: string, button: string, privacy?: string | null } | null } };

export type Home_TaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Home_TaFilter>;
}>;


export type Home_TaConnectionQuery = { __typename?: 'Query', home_taConnection: { __typename?: 'Home_taConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'Home_taConnectionEdges', cursor: string, node?: { __typename: 'Home_ta', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero?: { __typename: 'Home_taHero', title: string, subtitle?: string | null, description?: string | null, cta_primary?: { __typename: 'Home_taHeroCta_primary', text: string, href: string } | null, cta_secondary?: { __typename: 'Home_taHeroCta_secondary', text: string, href: string } | null } | null, mission_statement?: { __typename: 'Home_taMission_statement', title: string, content: string } | null, featured_departments?: Array<{ __typename: 'Home_taFeatured_departments', name: string, description: string, icon: string, href: string } | null> | null, recent_events?: Array<{ __typename: 'Home_taRecent_events', title: string, date: string, time: string, location: string, description: string, image?: string | null, category?: string | null } | null> | null, announcements?: Array<{ __typename: 'Home_taAnnouncements', title: string, date: string, content: string, priority?: string | null, category?: string | null } | null> | null, statistics?: Array<{ __typename: 'Home_taStatistics', number: string, label: string } | null> | null, quick_actions?: Array<{ __typename: 'Home_taQuick_actions', title: string, description: string, icon: string, href: string, color?: string | null } | null> | null, newsletter?: { __typename: 'Home_taNewsletter', title: string, description: string, placeholder: string, button: string, privacy?: string | null } | null } | null } | null> | null } };

export const Home_EnPartsFragmentDoc = gql`
    fragment Home_enParts on Home_en {
  __typename
  hero {
    __typename
    title
    subtitle
    description
    cta_primary {
      __typename
      text
      href
    }
    cta_secondary {
      __typename
      text
      href
    }
  }
  mission_statement {
    __typename
    title
    content
  }
  featured_departments {
    __typename
    name
    description
    icon
    href
  }
  recent_events {
    __typename
    title
    date
    time
    location
    description
    image
    category
  }
  announcements {
    __typename
    title
    date
    content
    priority
    category
  }
  statistics {
    __typename
    number
    label
  }
  quick_actions {
    __typename
    title
    description
    icon
    href
    color
  }
  newsletter {
    __typename
    title
    description
    placeholder
    button
    privacy
  }
}
    `;
export const Home_SiPartsFragmentDoc = gql`
    fragment Home_siParts on Home_si {
  __typename
  hero {
    __typename
    title
    subtitle
    description
    cta_primary {
      __typename
      text
      href
    }
    cta_secondary {
      __typename
      text
      href
    }
  }
  mission_statement {
    __typename
    title
    content
  }
  featured_departments {
    __typename
    name
    description
    icon
    href
  }
  recent_events {
    __typename
    title
    date
    time
    location
    description
    image
    category
  }
  announcements {
    __typename
    title
    date
    content
    priority
    category
  }
  statistics {
    __typename
    number
    label
  }
  quick_actions {
    __typename
    title
    description
    icon
    href
    color
  }
  newsletter {
    __typename
    title
    description
    placeholder
    button
    privacy
  }
}
    `;
export const Home_TaPartsFragmentDoc = gql`
    fragment Home_taParts on Home_ta {
  __typename
  hero {
    __typename
    title
    subtitle
    description
    cta_primary {
      __typename
      text
      href
    }
    cta_secondary {
      __typename
      text
      href
    }
  }
  mission_statement {
    __typename
    title
    content
  }
  featured_departments {
    __typename
    name
    description
    icon
    href
  }
  recent_events {
    __typename
    title
    date
    time
    location
    description
    image
    category
  }
  announcements {
    __typename
    title
    date
    content
    priority
    category
  }
  statistics {
    __typename
    number
    label
  }
  quick_actions {
    __typename
    title
    description
    icon
    href
    color
  }
  newsletter {
    __typename
    title
    description
    placeholder
    button
    privacy
  }
}
    `;
export const Home_EnDocument = gql`
    query home_en($relativePath: String!) {
  home_en(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Home_enParts
  }
}
    ${Home_EnPartsFragmentDoc}`;
export const Home_EnConnectionDocument = gql`
    query home_enConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Home_enFilter) {
  home_enConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Home_enParts
      }
    }
  }
}
    ${Home_EnPartsFragmentDoc}`;
export const Home_SiDocument = gql`
    query home_si($relativePath: String!) {
  home_si(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Home_siParts
  }
}
    ${Home_SiPartsFragmentDoc}`;
export const Home_SiConnectionDocument = gql`
    query home_siConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Home_siFilter) {
  home_siConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Home_siParts
      }
    }
  }
}
    ${Home_SiPartsFragmentDoc}`;
export const Home_TaDocument = gql`
    query home_ta($relativePath: String!) {
  home_ta(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Home_taParts
  }
}
    ${Home_TaPartsFragmentDoc}`;
export const Home_TaConnectionDocument = gql`
    query home_taConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Home_taFilter) {
  home_taConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Home_taParts
      }
    }
  }
}
    ${Home_TaPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home_en(variables: Home_EnQueryVariables, options?: C): Promise<{data: Home_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_EnQueryVariables, query: string}> {
        return requester<{data: Home_EnQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_EnQueryVariables, query: string}, Home_EnQueryVariables>(Home_EnDocument, variables, options);
      },
    home_enConnection(variables?: Home_EnConnectionQueryVariables, options?: C): Promise<{data: Home_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_EnConnectionQueryVariables, query: string}> {
        return requester<{data: Home_EnConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_EnConnectionQueryVariables, query: string}, Home_EnConnectionQueryVariables>(Home_EnConnectionDocument, variables, options);
      },
    home_si(variables: Home_SiQueryVariables, options?: C): Promise<{data: Home_SiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_SiQueryVariables, query: string}> {
        return requester<{data: Home_SiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_SiQueryVariables, query: string}, Home_SiQueryVariables>(Home_SiDocument, variables, options);
      },
    home_siConnection(variables?: Home_SiConnectionQueryVariables, options?: C): Promise<{data: Home_SiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_SiConnectionQueryVariables, query: string}> {
        return requester<{data: Home_SiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_SiConnectionQueryVariables, query: string}, Home_SiConnectionQueryVariables>(Home_SiConnectionDocument, variables, options);
      },
    home_ta(variables: Home_TaQueryVariables, options?: C): Promise<{data: Home_TaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_TaQueryVariables, query: string}> {
        return requester<{data: Home_TaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_TaQueryVariables, query: string}, Home_TaQueryVariables>(Home_TaDocument, variables, options);
      },
    home_taConnection(variables?: Home_TaConnectionQueryVariables, options?: C): Promise<{data: Home_TaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_TaConnectionQueryVariables, query: string}> {
        return requester<{data: Home_TaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Home_TaConnectionQueryVariables, query: string}, Home_TaConnectionQueryVariables>(Home_TaConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  